# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Portal < Formula
  desc "Portal is a quick and easy command-line file transfer utility from any computer to another 🖥️ 🌌 💻"
  homepage "https://github.com/ZinoKader/portal"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ZinoKader/portal/releases/download/v1.0.2/portal_1.0.2_Darwin_x86_64.tar.gz"
      sha256 "cbe47c10521ebecadabdc5a82a48172983c6a475c78b5fdab7bbe08fb0a24e73"

      def install
        bin.install "portal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ZinoKader/portal/releases/download/v1.0.2/portal_1.0.2_Darwin_arm64.tar.gz"
      sha256 "ad758e32381a518c7f741bb241be010a6191c3b8ea67da8d6c8e8a0829857232"

      def install
        bin.install "portal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ZinoKader/portal/releases/download/v1.0.2/portal_1.0.2_Linux_arm64.tar.gz"
      sha256 "64361a8b409e9c465b665c5c8f8e6ee8581b3527306ba85f406ec747eda3bdda"

      def install
        bin.install "portal"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ZinoKader/portal/releases/download/v1.0.2/portal_1.0.2_Linux_x86_64.tar.gz"
      sha256 "3f193c051eb48715cbbf25b5a8faced48e9dcb3f2e498371c4359bd3d959612f"

      def install
        bin.install "portal"
      end
    end
  end
end
