# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Portal < Formula
  desc "Portal is a quick and easy command-line file transfer utility from any computer to another 🖥️ 🌌 💻"
  homepage "https://github.com/SpatiumPortae/portal"
  version "1.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/SpatiumPortae/portal/releases/download/v1.0.5/portal_1.0.5_macOS_arm64.tar.gz"
      sha256 "4864eef0d38ee71a21bd574488128e5fd136f5bb3f87067b75a95f8bab4f3797"

      def install
        bin.install "portal"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/SpatiumPortae/portal/releases/download/v1.0.5/portal_1.0.5_macOS_x86_64.tar.gz"
      sha256 "2232459040387a08f92b0aae14d924c0d9812287477033dff138df02dae814ab"

      def install
        bin.install "portal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/SpatiumPortae/portal/releases/download/v1.0.5/portal_1.0.5_Linux_x86_64.tar.gz"
      sha256 "0b960c0ecc7c994e898f67904eaf9e61d689faff2f7bf3108d24f8ebe0c6330c"

      def install
        bin.install "portal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SpatiumPortae/portal/releases/download/v1.0.5/portal_1.0.5_Linux_arm64.tar.gz"
      sha256 "4804adb6686da830e433a1ec16da2e5898b26e64aff7b6672828804a83b55bef"

      def install
        bin.install "portal"
      end
    end
  end
end
