# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Portal < Formula
  desc "Portal is a quick and easy command-line file transfer utility from any computer to another 🖥️ 🌌 💻"
  homepage "https://github.com/SpatiumPortae/portal"
  version "1.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/SpatiumPortae/portal/releases/download/v1.0.4/portal_1.0.4_macOS_arm64.tar.gz"
      sha256 "3464eedce2c9c2a2ddb66cde45590a7813b42785068bc502a2a9de8a48171888"

      def install
        bin.install "portal"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/SpatiumPortae/portal/releases/download/v1.0.4/portal_1.0.4_macOS_x86_64.tar.gz"
      sha256 "0d57bf7f363f0198784c80f736708a1aabc9e65182bbdaa826fee4a01af67371"

      def install
        bin.install "portal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SpatiumPortae/portal/releases/download/v1.0.4/portal_1.0.4_Linux_arm64.tar.gz"
      sha256 "a85c125a831891188ffd8aa15e286ce7266c1548226c4835f4439c8767db226a"

      def install
        bin.install "portal"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/SpatiumPortae/portal/releases/download/v1.0.4/portal_1.0.4_Linux_x86_64.tar.gz"
      sha256 "3a3749165d81d70e90cc26acd93dcb55cb3e265ccff853605e785c9271e575ae"

      def install
        bin.install "portal"
      end
    end
  end
end
